# Using spring-ai-starter-mcp-server-webmvc
spring.ai.mcp.server.name=sbmcp
server.port=8080
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.ai.mcp.server.streamable-http.keep-alive-interval=30s